### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by ifelsefi** [krlmlr/bindrcpp#9]
Hi

I am unable to compile on CentOS 7.5 using [Spack package manager](https://spack.io) with R version 3.5.1 and GCC 6.3.0.

The error:

```
In file included from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/bits/uniform_int_dist.h:35:0,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/bits/stl_algo.h:66,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/algorithm:62,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/r-rcpp-0.12.16-poo7hwdeem4fw5somrq2fde4dqb6jhnu/rlib/R/library/Rcpp/include/RcppCommon.h:72,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/r-rcpp-0.12.16-poo7hwdeem4fw5somrq2fde4dqb6jhnu/rlib/R/library/Rcpp/include/Rcpp.h:27,
                 from create.cpp:1:
/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/limits:1598:7: internal compiler error: Illegal instruction
       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
       ^~~
In file included from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/bits/uniform_int_dist.h:35:0,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/bits/stl_algo.h:66,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/algorithm:62,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/r-rcpp-0.12.16-poo7hwdeem4fw5somrq2fde4dqb6jhnu/rlib/R/library/Rcpp/include/RcppCommon.h:72,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/r-rcpp-0.12.16-poo7hwdeem4fw5somrq2fde4dqb6jhnu/rlib/R/library/Rcpp/include/Rcpp.h:27,
                 from test.cpp:1:
/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/limits:1598:7: internal compiler error: Illegal instruction
       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
       ^~~
In file included from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/bits/uniform_int_dist.h:35:0,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/bits/stl_algo.h:66,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/algorithm:62,
                 from /pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/r-rcpp-0.12.16-poo7hwdeem4fw5somrq2fde4dqb6jhnu/rlib/R/library/Rcpp/include/RcppCommon.h:72,
                 from ../inst/include/bindrcpp_types.h:4,
                 from ../inst/include/bindrcpp_RcppExports.h:7,
                 from ../inst/include/bindrcpp.h:7,
                 from RcppExports.cpp:4:
/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/include/c++/6.3.0/limits:1598:7: internal compiler error: Illegal instruction
       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
       ^~~
0xacf93f crash_signal
        /pbtech_mounts/softlib001/apps/EL7/spack/var/spack/stage/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/gcc-6.3.0/gcc/toplev.c:333
0xacf93f crash_signal
        /pbtech_mounts/softlib001/apps/EL7/spack/var/spack/stage/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/gcc-6.3.0/gcc/toplev.c:333
Please submit a full bug report,
with preprocessed source if appropriate.
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
See <http://gcc.gnu.org/bugs.html> for instructions.
make: *** [create.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [test.o] Error 1
0xacf93f crash_signal
        /pbtech_mounts/softlib001/apps/EL7/spack/var/spack/stage/gcc-6.3.0-4h22ps2wttqbknmpnjft4h5bd2uvzndl/gcc-6.3.0/gcc/toplev.c:333
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘bindrcpp’
* removing ‘/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/r-bindrcpp-0.2.2-csfmjxgfw6y3v62haki6qraxcthnplac/rlib/R/library/bindrcpp’
```

[spack-build.txt](https://github.com/krlmlr/bindrcpp/files/2581477/spack-build.txt)
